#!/usr/bin/env python3
#
# Check if the list of groups generated by find-groups.sh looks right.

import sys
import re
import staffeli.canvas as canvas


course = canvas.Course()
can = canvas.Canvas()
users = list(can.all_students(course.id))
user_ku_ids = [u['login_id'].split('@')[0] for u in users]

def ku_id_exists(ku_id):
    return ku_id in user_ku_ids

def check(path):
    with open(path) as f:
        contents = f.read().strip()
    groups = [line.split(' ') for line in contents.split('\n')]

    parse_error = False
    for group in groups:
        for member in group:
            if not re.match(r'[a-z]{3}[0-9]{3}', member):
                print('Group member looks wrong: {}'.format(repr(member)))
                parse_error = True
    if parse_error:
        return 1

    id_error = False
    members_so_far = []
    for group in groups:
        for member in group:
            if member in members_so_far:
                print('Member {} is already present in another group.'.format(repr(member)))
                continue
            members_so_far.append(member)
            if not ku_id_exists(member):
                print('Member {} does not appear to exist in the course.'.format(member))
                continue

    if id_error:
        return 1

    return 0
    
sys.exit(check(sys.argv[1]))
